name: "validate, test, build and publish features"
on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
    workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
    test:
      name: ${{ format('{0} ({1})', matrix.feature, matrix.image ) }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          feature: ["easy-container-hooks", "pyenv"]
          image: ["alpine", "debian"]
      steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
            fetch-depth: 2
        - uses: extractions/setup-just@v1
        - name: set paths-filter base
          id: set-pf-base
          run: |
            echo "BASE=$(git rev-parse --short HEAD~1)" >> $GITHUB_OUTPUT
        - uses: dorny/paths-filter@v2
          id: changed
          with:
            # base is ignored on pull-requests
            base: ${{ steps.set-pf-base.outputs.base  }}
            filters: |
              feature: [ 'features/**/${{ matrix.feature }}/**' ]
        - if: steps.changed.outputs.feature == 'true'
          run: |
            npm install -g @devcontainers/cli
            just test features/${{ matrix.feature }} ${{ matrix.image }}
    build:
      name: ${{ format('{0} ({1})', matrix.feature, matrix.image ) }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          feature: ["easy-container-hooks", "pyenv"]
          image: ["alpine", "debian"]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: extractions/setup-just
        - run: |
            npm install -g @devcontainers/cli
            just publish features/${{ matrix.feature }}
            just generate-docs features/${{ matrix.feature }}
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            branch: auto-doc-update-${{ github.run_id }}
            create_branch: true
            commit_message: Automated documentation update for features.
            file_pattern: features/src/**/README.md
        - run: |
            gh pr create                               \
              --head auto-doc-update-${GITHUB_RUN_ID}  \
              --fill-first